### ISSUE TITLE
Python complains of no frontend_connector

### ISSUE THREAD

**Issue by kd4e** [MattMills/radiocapture-rf#20]
I'm a Python newbie.
I'm running this on the Lubuntu-based DragonOS_Focal.
I've been unable to find a reference to frontend_connector in an Internet Search.
I tried "sudo pip install frontend_connector" and it came up empty.
Suggestions, please?
I'm trying to access a Motorola Type II Smartnet system and nothing else works.
Thanks!

**Comment by MattMills** [comment]
Frontend_connector (a terrible name) is a relative include, it's right here: https://github.com/MattMills/radiocapture-rf/blob/master/frontend_connector.py

I'd guess you're not cd'd into the directory you cloned into while starting the app. None of my pieces are setup right now to be installed via pip or are "standardized" (IE: python/dist-packages) style python packages, I should work on that.

That said, my smartnet decoder is not very well tested and smartnet is a pretty goofy protocol, so I'd be a bit surprised if other stuff didn't work and it did.

**Comment by MattMills** [comment]
IE: 
```
cd /opt/radiocapture-rf
python3 ./overseer.py
```

Oh and the smartnet demodulator isn't able to discover channels, you need to have all the voice channels configured in the config with the right channel ID for them to be captured.

**Comment by kd4e** [comment]
Sure appreciate your reply! I'll try these instructions and see what happens. I'll likely have more questions! BTW1: I've sent your work to both DragonOS and MX Linux support people asking them to look into adding it. No one else seems able to handle the Motorola Type II Smartnet. BTW2 :Our son has a friend who says he has Python certification (he's a bit of an unmotivated mess) - so he may be a local source of help - so I don't pester you more than necessary (if he can get out of bed long enough). Thanks!

**Comment by kd4e** [comment]
OK, I must have missed a step or two somewhere.
There was no /opt/radiocapture-rf folder - so I created one.
Then I copied and pasted your frontend_connector.py and put it there.
But python3 does not find "overseer.py"

**Comment by kd4e** [comment]
Well, how about that, poking around I just realized that I'd completely missed your "How to install:
WARNING WARNING WARNING: Install instructions are still work in progress. These are my install instruction notes from a fresh ubuntu 20.04 server install" page. Told you I was a newbie. I'll run through these instructions and see what I can break ... err, get to work ... sigh.

**Comment by kd4e** [comment]
OK, got as far as "git clone git@github.com:MattMills/op25.git"
That's generating an error message saying "Permission denied (publickey)"
"fatal: Could not read from remote repository."
"Please make sure you have the correct access rights and the repository exists."

**Comment by kd4e** [comment]
New error "/opt does not appear to contain CMakelists.txt"
How is that resolved, please?

**Comment by kd4e** [comment]
NOTE: I'm having to use sudo for most of this - is that expected?

**Comment by kd4e** [comment]
Are these all intended to be comments or is a single "#" different than a double "##"?
```
#activemq stomp enable
#activemq instance enable
#activemq start
#redis start

#if cluster:
#activemq bind 0.0.0.0
#redis bind 0.0.0.0
#firewall warning
#put all redis servers into the config
#set hosts file hostname to LAN IP not 127.0.0.1
#systemctl files install
```

**Comment by MattMills** [comment]
They're comment-notes, I didn't finish that part of the instructions yet, enabling stomp would be inserting
```
<transportConnector name="stomp" uri="stomp://localhost:61613"/>
``` 

into /etc/activemq/instances-available/main/activemq.xml in the transportConnectors section, enabling the instance is 

```ln -s /etc/activemq/instances-available/main /etc/activemq/instances-enabled/main```

then starting up those two services should be a `systemctl start redis` and `systemctl start activemq` the remainder is for installs with multiple computers. You don't need op25 unless you want to do P25 systems. 

To startup you'll need to either tweak the systemd config files and put them in place to start as services, or manually start by running rc_frontend/receiver.py (which handles RF and channelization) and overseer.py (which handles system demodulation and audio capture).

**Comment by MattMills** [comment]
Obviously things may be different for your specific distro, the instructions are for Ubuntu.

**Comment by kd4e** [comment]
Used Docker to install rdio-scanner
Set up a config-bulloch-rtl.json for a multi system.
When I run "sudo ./recorder --config=config-bulloch1-rtl.json" I get an error "usb_claim_interface error -6 ... Failed parsing Config: Failed to open rtlsdr device. /root/.gnradio/prefs/vmcircbuf_default_factory: No such file or directory vmcircbuf_createfilemapping: createfilemapping is not available ... and more

**Comment by MattMills** [comment]
OK, That's different software not related to this.
